### ISSUE TITLE
Ensure start/end calls match up

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#11]
In #2 @pixelzoom said:

> :star2: It's up to the client to ensure that phetEvents.start and end calls match up. A programming error (e.g., missing 'end' call) could be very difficult to find. The API should prevent this by identifying and enforcing start/end pairs. Ie, when you call 'end', the implementation is able to verify that it's matching 'start' is on the top of the stack.

Can you suggest a way of doing this? Are you thinking of adding an argument to the end function?

**Comment by samreid** [comment]
Not sure how to implement this now given that we have gone to the `arch && arch.method` pattern.

**Comment by samreid** [comment]
Oh I forgot JS returns the value of the last expression in the && train.  Perhaps we can use that (but will break our convention for stripping lines that start with `arch && arch.method`.  Perhaps another convention--a var name that we always use that can be stripped such as `var archID=arch && arch.method'

**Comment by samreid** [comment]
After discussion with @jonathanolson we decided to try something like:

```js
var archID = arch && arch.start();
```

This will presumably be minified to:

```js
var archID = false;
```

Since this var is unused, it may also be stripped by the minifier.

**Comment by samreid** [comment]
> Since this var is unused, it may also be stripped by the minifier.

Even if this var is not stripped, I don't expect it to be a very large burden in terms of kb or startup time.

**Comment by samreid** [comment]
I built a version and it is still showing arch as simply `arch`.  Not sure how to trigger it to know arch=false.  @jonathanolson can you help?  I couldn't figure out how assert is doing this.

**Comment by samreid** [comment]
Oh maybe I am supposed to put this in uglify2.compress.global_defs.  Checking....

**Comment by samreid** [comment]
Oh nice,
```js
        console.log( 'huggermugger' );
        var archID = arch && arch.start( 'dropped-mannequin' );
        model.appliedForce = 0;
        arch && arch.end( archID );
```
gets minified to:
```js
console.log("huggermugger");t.appliedForce=0
```

This seems good to go.  Reassigning to @pixelzoom for feedback.

**Comment by samreid** [comment]
Oh wait, two remaining issues.  First, what does the minified code look like when arch is turned on?

```js
console.log("huggermugger");var e=!0&&(!0).start("dropped-mannequin");t.appliedForce=0,!0&&(!0).end(e)
```

Second issue: how to enable/disable arch for production builds?  Perhaps a new gruntfile option?  Or if it detects arch in the preloads then it sets arch to be true for the uglify?  This latter seems best.

**Comment by samreid** [comment]
Actually, can I get @pixelzoom to review the plan above before I spend time building it?

**Comment by pixelzoom** [comment]
Reading through above comments, I'm not clear on what "the plan" is.  And I'm not sure how it addresses the issue of ensuring that start/end calls match up.

**Comment by samreid** [comment]
The last remaining issue for #11 is:

> Second issue: how to enable/disable arch for production builds? Perhaps a new gruntfile option? Or if it detects arch in the preloads then it sets arch to be true for the uglify? This latter seems best.

The uglify option in Gruntfile.js looks like:

```js
            uglify2: {
              output: {
                inline_script: true // escape </script
              },
              compress: {
                global_defs: {
                  // global assertions
                  assert: false,
                  assertSlow: false,
                  // scenery logging
                  sceneryLog: false,
                  sceneryLayerLog: false,
                  sceneryEventLog: false,
                  sceneryAccessibilityLog: false,
                  phetAllocation: false
                },
                dead_code: true
              }
            }
```

The question is how to put arch:true or arch:false in the global_defs.  My thought was to dynamically check the list of dependencies, and put arch:true if arch is found as a dependency, otherwise putting arc:false.  Do you think this will work well?

**Comment by pixelzoom** [comment]
Seems like that should work. Something like:

> var archRequired = _.find( pkg.preLoad.split( ' ' ), function( repo ) { return repo === '../arch/js/arch.js'; } );

**Comment by samreid** [comment]
Just setting the global_defs:arch to be true or false won't work.  That sets it as a global constant for the compression.  We need to selectively add arch to the global_defs if arch is disabled, so that it will be stripped out.

**Comment by samreid** [comment]
Fixed above.  I tested this by building Forces and Motion Basics with and without arch in the package.json, and inspecting the built html file.  @pixelzoom review if you wish.
