### ISSUE TITLE
phetEvents.wrap and trigger function names don't communicate what they do.

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#12]
In #2, @pixelzoom said:

> phetEvents.wrap and trigger function names don't communicate what they do.

Can you recommend better names?

**Comment by samreid** [comment]
I removed `wrap` and in my opinion, trigger is sufficiently clear and well documented that it can be kept.  I find startEnd() to be awkward--signifying the implementation of the method rather than how it is intended to be used--as a signal for an atomic event.  Perhaps now that the API is simpler and trigger is better documented, it is okay to keep trigger as it is.

**Comment by pixelzoom** [comment]
Looks good, closing.
