### ISSUE TITLE
pattern for instrumenting UI components

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#14]
In #2 @pixelzoom said:

> Instrumentation of more components (buttons, sliders,...) should be explored to determine a 'good' API for instrumenting UI components.

**Comment by samreid** [comment]
Sun buttons, sliders, etc have been instrumented and needs review by @jbphet or @pixelzoom.

**Comment by pixelzoom** [comment]
@samreid I can take a look with you on Monday.

**Comment by pixelzoom** [comment]
Looking at UI components that have been instrumented so far, I see this pattern in their constructors:

```js
    options = _.extend( {
      //...
      componentID: null
    }, options );

    Node.call( this );

    this.componentID = options.componentID;
    //...
    this.mutate( options )
```

So there would be some economy to be gained from having Node support componentID.  Has that been discussed? What are the pros and cons?

**Comment by pixelzoom** [comment]
Looking at UI components that have been instrumented so far, I see this pattern in their constructors:

```js
    options = _.extend( {
      //...
      componentID: null
    }, options );

    Node.call( this );

    this.componentID = options.componentID;

    //...

    this.mutate( options )
```

So there would be some economy to be gained from having Node support componentID.  Ie, the above becomes:

```js
    Node.call( this );
    //...
    this.mutate( options )
```

Has that been discussed? What are the pros and cons?

**Comment by pixelzoom** [comment]
Looking at beers-law-lab.BLLDropperNode ...  I think I would move the responsibility for setting the componentID into the supertype (scenery-phet.EyeDropperNode).  EyeDropperNode is after all a reusable component. And it already has `options.buttonComponentID`, so seems like it should also have `options.componentID`, and should be responsible for registering the component, ie:

`options.componentID && together && together.addComponent( this );`

So this would seem to indicate that the pattern for reusable components is that they should have `options.componentID` (and possibly options for setting sub-component IDs) and be responsible for registering the component if it has been assigned an ID.

**Comment by pixelzoom** [comment]
Problem: Calling together.addComponent immediately tries to update the object. This won't play nice with subtyping.  If together.addComponent is called in the supertype constructor, we'll be trying to change a partially-constructed object.

**Comment by samreid** [comment]
> So there would be some economy to having Node support componentID.

@jonathanolson suggested good reasons why Node shouldn't support componentID directly, and that we may want to override scenery/Node prototype in Joist, but I don't recommend doing this now.

I also moved @pixelzoom's last comment to a new issue https://github.com/phetsims/together/issues/20 and will close this issue.
