### ISSUE TITLE
code review for potential merge into master

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arch#2]
This is a consolidation of https://github.com/phetsims/axon/issues/34, https://github.com/phetsims/joist/issues/167 and https://github.com/phetsims/sun/issues/120.

Review arch and the 'arch' branches of axon, joist and sun. Sim examples are in the 'arch' branches of balancing-act and fluid-pressure-and-flow.

Evaluate whether this approach to data collection is (a) suitable for merging into master, and (b) if the design seems scalable enough for future studies or (c) if we should make API changes before proliferating usage.

It would be nice to review our strategy and merge it to master before the next study. The study begins on Monday October 27, so having the review complete by Monday October 13 would give us plenty of time to address the review issues and merge to master, with enough time for testing.

**Comment by samreid** [comment]
> All of the messages (from Property, PropertySet, ObservableArray, ABSwitch, CheckBox,...) have an 'id'. The name 'id' and setID doesn't tell us it's related to data collection. And there's nothing in the underlying arch API that requires an id, so we end up with this over and over: { id: id, ... }. If an id is something we think is needed by messages, then either phetEvents should require it, or there should be another API on top of phetEvents that requires it.

This has been renamed to componentID and documented in together/arch.js.  Arch now requires a componentID.

**Comment by samreid** [comment]
All subissues addressed, closing.

**Comment by pixelzoom** [comment]
This issue has been archived in https://github.com/phetsims/together/issues/27.
