### ISSUE TITLE
Unify event names across iframe API, state API and arch API

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#20]
We have three distinct APIs at the moment:
* accessing & setting data across iframes (developed in together repo)
* save/restore state (mostly defined by axon + joist)
* arch API (developed here in arch)

These APIs have been developed independently and often the names of components do not match up across the representations.  We should attempt to (a) unify the names as much as possible or (b) standardize on a convention that allows straightforward mapping between the APIs.

**Comment by samreid** [comment]
One idea for unification: pass parentID or parentComponentID to children, so they can use that to construct their componentID.

**Comment by samreid** [comment]
The above idea: would be one way to unify & disambiguate names, but would have to be propagated *everywhere*.

**Comment by samreid** [comment]
I really like the idea of using parentIDs to construct componentID's--that would go a long way to disambiguating which component is being used.  For instance, if there are 2 reset all buttons in a sim, instead of each one having componentID "resetAllButton" they would have unique IDs: `sim.screens[0].view.resetAllButton` and `sim.screens[1].view.resetAllButton`.

**Comment by samreid** [comment]
One drawback of the above approach.  It might make some things *seem* accessible over the iframe API that *aren`t* accessible over the iframe API.  For instance, if the resetAllButton was stored in a closure instead of an instance variable, then it couldn't be accessed over the iframe API.

**Comment by pixelzoom** [comment]
My concerns with this approach:

• Putting the parent id in all APIs will be a huge task, and a huge burden going forward.
• Component IDs that reflect the structure of the code means that we will be breaking the API whenever we change the structure of the code.
• Breaking the API when changing code structure will be a disincentive to change code structure, resulting in sub-standard code.

**Comment by samreid** [comment]
Questions and thoughts from today's meeting:

Should we create our own maps for each simulation API feature?
Are we supporting a constant API?
If componentID is tied to implementation--we won’t want to refactor since it would break APIs.
CM: Arch could fill in the screen name?
JO: Good to decouple from JSON as well so save states will work across refactorings.
JO: Each sim exports a logical API structure, and we have to map it into implementation.  May have to pass parentIDs if you have multiple instances of similar things in different contexts.

**Comment by samreid** [comment]
componentIDs no longer reflect structure of the code and will not break its API.  Components have a unique ID not assigned by arch.  We'll continue work on this in other issues.
