### ISSUE TITLE
move arch stub out of axon.Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/arch#21]
The stub for arch is created by axon.Property.initArch, and it's called from joist.Sim. Let's find a better place for this.

**Comment by samreid** [comment]
The arch stub must be created before any Property is instantiated.  Where do you think this should go?

**Comment by pixelzoom** [comment]
It will presumably be used in other repos other than AXON (I see 1 use in sun so far). So the current order dependency on Property doesn't seem like a good reason to put the stub in Property.  Ideally, I think the stub should live in arch, and be loaded before the sim starts (ala query-parameters.js).

**Comment by pixelzoom** [comment]
Discussed via Skype voice. We're going to ditch the stub entirely, and use this pattern for calling arch functions (see #23):

> arch && arch.trigger(...);

This will be less likely to cause performance issues (no stub calls happen).
And note that (like assert) we're not going to attach the arch global to window.phet.

**Comment by samreid** [comment]
This stub is gone, @pixelzoom review if you wish.

**Comment by pixelzoom** [comment]
I don't see a stub in check-arch.js, I see:

> window.arch = window.arch || null;

Just curious... Why is it important that window.arch is null instead of undefined?

**Comment by samreid** [comment]
I was calling window.arch=null the world's smallest "stub"! 

If we set window.arch=undefined, then using the pattern `arch && arch.method` yields:
<exception>: ReferenceError: arch is not defined

**Comment by pixelzoom** [comment]
Thanks for clarification, closing.
