### ISSUE TITLE
Clean up globals, probably with IIFE

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#22]
See https://github.com/phetsims/tasks/issues/160#issuecomment-72300170

> @samreid arch.js is creating a lot of globals that don't appear to be used outside of arch.js: targets, websocketURL, websocketPath, webSocket, bufferedWebSocket, storedMessages, storeMessageListener. Is this intentional/necessary? Can we encapsulate these in an IIFE?

Yes, I think so.  Let's create an arch issue and investigate there.

**Comment by samreid** [comment]
I put everything in an IIFE, @pixelzoom review if you wish.

**Comment by pixelzoom** [comment]
Looks great, closing.
