### ISSUE TITLE
Check before using arch by using arch && arch.trigger/etc

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#23]
After discussion with @pixelzoom, we decided to follow the same pattern that we have for assert here for arch.  Instead of creating a stub we will check for the existence of arch with:

```js
arch && arch.trigger(...);
```

This will need to change everywhere arch is used.

We thought this would have the following advantages (same as assert):
1. No performance penalties if arch is not used
2. Ability to strip out arch messages easily.

Reassigned to @samreid

**Comment by samreid** [comment]
Fixed above, @pixelzoom do you want to take a look?

**Comment by pixelzoom** [comment]
In ObservableArray, I think things would read a little better if the order were changed from (for example):
> arch && this.sendPhetEvents && arch.end();
to 
> this.sendPhetEvents && arch && arch.end();

In Property, I'm a little confused. I don't see the `arch && arch.method` pattern. I see `arch.method` with no test for whether `arch` is defined. Please clarify.

**Comment by pixelzoom** [comment]
Ah, I was reviewing on of the above commits for Property, didn't realize there was a more recent commit. So disregard my question about Property.  But I do have the same comment for Property as I did for ObservableArray.  That is, this (for example):

> 94  var archID = arch && this.sendPhetEvents && arch.start( 'model', this.propertyID, 'Property', 'changed', { value: value } );

would be a bit nicer if written as:

> 94  var archID = this.sendPhetEvents && arch && arch.start( 'model', this.propertyID, 'Property', 'changed', { value: value } );

This is admittedly a nit, but keep the `arch && arch.method` pattern intact, rather than sticking another test in the middle of it.

**Comment by samreid** [comment]
I originally put arch && this.sendPhetEvents because I thought the minifier might be looking for lines beginning with arch&&.  While I can now see this is not the case, I still think it is important to put the arch check first, since turning off arch should turn off all arch-related-features, including checking the value for `this.sendPhetEvents`.
