### ISSUE TITLE
Can we delete arch?

### ISSUE THREAD

**Issue by samreid** [phetsims/arch#25]

**Comment by samreid** [comment]
All open issues have been moved to https://github.com/phetsims/together/issues and the code has been moved to https://github.com/phetsims/together.  The only reason I can think of to keep this repository is for keeping the code history for arch.js but that doesn't seem too important to me.  OK to delete this repo @pixelzoom @jonathanolson @jbphet @aaronsamuel137 ?

**Comment by jonathanolson** [comment]
No preference.

**Comment by aaronsamuel137** [comment]
I'm okay to delete it.

**Comment by pixelzoom** [comment]
OK with me to delete it.

**Comment by pixelzoom** [comment]
The only arch issue that has historical value to me is https://github.com/phetsims/arch/issues/2 (code review).  Should I move that issue over to together?

**Comment by samreid** [comment]
Ah thanks, I hadn't considered moving closed issues.  I can move it, or feel free if you would prefer to do so.

**Comment by pixelzoom** [comment]
I'll move it.

**Comment by pixelzoom** [comment]
#2 archived in https://github.com/phetsims/together/issues/27

**Comment by samreid** [comment]
I strolled through the other closed issues and none stuck out as ones that needed to be archived.  I'll delete the arch repo soon.
